module.exports = {
  // Header
  "header.login": "Masuk",
  "header.logout": "Keluar",
  "header.settings": "Pengaturan",

  // Navigation / Sidebar
  "nav.dashboard": "Dasbor",
  "nav.competitions": "Kompetisi",
  "nav.users": "Pengguna",
  "nav.schedule": "Jadwal",
  "nav.settings": "Pengaturan",
  "nav.overview": "Ringkasan",
  "nav.bracket": "Braket",
  "nav.participants": "Peserta",
  "nav.ranking": "Peringkat",
  "nav.competition_menu": "Kompetisi",

  // Common Actions
  "action.save": "Simpan",
  "action.cancel": "Batal",
  "action.delete": "Hapus",
  "action.edit": "Edit",
  "action.add": "Tambah",
  "action.confirm": "Konfirmasi",
  "action.search": "Cari...",
  "action.filter": "Saring",
  "action.view_details": "Lihat Detail",

  // Common Statuses
  "status.draft": "Draf",
  "status.published": "Dipublikasikan",
  "status.publish": "Dipublikasikan",
  "status.registered": "Pendaftaran",
  "status.ongoing": "Berlangsung",
  "status.finished": "Selesai",
  "status.scheduled": "Dijadwalkan",
  "status.approved": "Disetujui",
  "status.pending": "Menunggu",
  "status.paid": "Lunas",
  "status.unpaid": "Belum Bayar",

  // Public Pages - Phase 2
  "public.overview.rules": "Aturan",
  "public.filter.all_categories": "Semua Kategori",
  "public.filter.all_subjects": "Semua Mata Pelajaran",
  "public.overview.prize": "Total Hadiah",
  "public.overview.timeline": "Jadwal Pelaksanaan",
  "public.overview.timeline_desc": "Dari pendaftaran hingga grand final",
  "public.overview.registration": "Pendaftaran",
  "public.overview.qualification": "Babak Kualifikasi",
  "public.overview.grandfinal": "Babak Grand Final",
  "public.overview.groups": "Grup",
  "public.overview.champion": "Penobatan Juara",
  "public.overview.1st_place": "Juara 1",
  "public.overview.2nd_place": "Juara 2",
  "public.overview.3rd_place": "Juara 3",

  "public.schedule.title": "Jadwal Pertandingan",
  "public.schedule.days": "Hari",
  "public.schedule.hours": "Jam",
  "public.schedule.mins": "Menit",
  "public.schedule.secs": "Detik",
  "public.schedule.match_start": "Pertandingan Dimulai",
  "public.schedule.next_phase": "Fase Selanjutnya",
  "public.schedule.no_upcoming": "Tidak Ada Fase Mendatang",
  "public.schedule.not_released": "Jadwal untuk kompetisi ini belum dirilis.",
  "public.schedule.desc": "Jadwal pertandingan terbaru dan status turnamen.",
  "public.schedule.empty": "Belum ada jadwal yang tersedia.",
  "public.schedule.search": "Cari peserta atau sekolah...",
  "public.schedule.time": "Waktu",
  "public.schedule.match": "Pertandingan",
  "public.schedule.phase": "Fase",
  "public.schedule.status": "Status",

  "public.participants.title": "Peserta",
  "public.participants.desc": "Peserta yang terdaftar dalam kompetisi ini.",
  "public.participants.search": "Cari peserta...",
  "public.participants.name": "Nama Peserta",
  "public.participants.school": "Asal Sekolah",
  "public.participants.seed": "Seed",

  "public.ranking.title": "Peringkat",
  "public.ranking.desc": "Peringkat saat ini berdasarkan poin yang diperoleh.",
  "public.ranking.search": "Cari peringkat...",
  "public.ranking.rank": "Peringkat",
  "public.ranking.name": "Nama",
  "public.ranking.score": "Skor",

  "public.match.title": "Detail Pertandingan",
  "public.match.back": "Kembali",

  "public.ranking.empty": "Data peringkat belum tersedia.",
  "public.ranking.not_ready": "Peringkat akan muncul setelah pertandingan selesai.",

  "public.bracket.title": "Braket",
  "public.bracket.desc": "Visualisasi turnamen.",
  "public.bracket.empty": "Braket belum tersedia.",

  "public.dashboard.empty": "Belum ada kompetisi",
  "public.dashboard.empty_desc": "Nantikan kompetisi mendatang.",
  "status.coming_soon": "Segera Hadir",
  "public.dashboard.details": "Detail",
  "footer.rights": "© 2026 GameForSmart. Hak cipta dilindungi undang-undang.",

  "public.participants.empty": "tidak menemukan peserta.",
  "public.participants.category": "Kategori",
  "public.participants.subject": "Mata Pelajaran",
  "public.participants.independent": "Independen",
  "public.participants.general": "Umum",
  "public.schedule.general": "Umum",

  "pagination.show": "Tampilkan",
  "pagination.entries": "data",
  "pagination.page": "Halaman",
  "pagination.of": "dari",

  "bracket.fit": "Sesuaikan ke layar",
  "bracket.fullscreen": "Layar Penuh",
  "bracket.exit_fullscreen": "Keluar Layar Penuh",

  "display.loading_scoreboard": "Memuat Papan Skor...",
  "display.round": "Ronde",
  "display.category": "Kategori",
  "display.match_roster": "Daftar Peserta Pertandingan",
  "display.match_timer": "Waktu Pertandingan",
  "display.final": "Final",

  // Admin Phase 3
  "admin.competitions.title": "Data Kompetisi",
  "admin.competitions.add": "Tambah",
  "admin.competitions.all_status": "Semua Status",
  "admin.competitions.poster": "Poster",
  "admin.competitions.name": "Nama",
  "admin.competitions.category": "Kategori",
  "admin.competitions.subject": "Mata Pelajaran",
  "admin.competitions.status": "Status",
  "admin.competitions.participants": "Peserta",
  "admin.competitions.action": "Aksi",
  "admin.competitions.empty": "Tidak ada kompetisi ditemukan.",
  "admin.competitions.empty_desc": "Coba ubah kata kunci pencarian atau filter.",
  "admin.competitions.public_page": "Halaman Publik",
  "admin.competitions.delete_confirm": "Apakah Anda yakin ingin menghapus kompetisi ini? Tindakan ini tidak dapat dibatalkan.",
  "admin.competitions.delete_success": "Berhasil dihapus.",
  "admin.competitions.delete_error": "Gagal menghapus: ",
  "admin.competitions.total_prize": "Total Hadiah",
  "admin.competitions.prize_allocation": "Alokasi Hadiah",
  "admin.competitions.detail": "Detail Kompetisi",

  // Admin Phase 4
  "admin.tabs.registration": "Pendaftaran",
  "admin.tabs.qualification": "Kualifikasi",
  "admin.tabs.schedule": "Jadwal",
  "admin.tabs.group_stage": "Fase Grup",
  "admin.tabs.champion": "Juara",
  "admin.tabs.standings": "Klasemen",
  "admin.actions.move_to_finalist": "Pindahkan ke Finalis",

  "admin.standings.title": "Klasemen",
  "admin.standings.insert_to_bracket": "Masukkan ke Braket",
  "admin.standings.insert_random": "Masukkan Acak",
  "admin.standings.insert_selected": "Masukkan Pilihan",
  "admin.standings.select_all": "Pilih Semua",
  "admin.standings.eligible_finalists": "Finalis Memenuhi Syarat",
  "admin.standings.bracket_info": "Info Braket",
  "admin.standings.no_finalists": "Tidak ada finalis ditemukan. Pindahkan peserta ke finalis dari tab Kualifikasi terlebih dahulu.",
  "admin.standings.modal_title": "Tambah ke Braket",
  "admin.standings.locked_filter": "Peserta disaring berdasarkan kategori dan subjek braket ini.",

  // Admin Phase 5
  "admin.users.title": "Peserta",
  "admin.users.desc": "Kelola semua tim terdaftar, individu, dan penempatan mereka.",
  "admin.users.registered": "Peserta Terdaftar",
  "admin.users.overview": "Ringkasan semua entri di seluruh kompetisi Anda.",
  "admin.users.teams": "Tim",
  "admin.users.individuals": "Individu",
  "admin.users.table.team_info": "Info Tim",
  "admin.users.table.participant_info": "Info Peserta",
  "admin.users.table.competition": "Kompetisi",
  "admin.users.table.contact": "Kontak",
  "admin.users.table.seed": "Penempatan (Seed)",
  "admin.users.table.status": "Status",
  "admin.users.table.action": "Aksi",
  "admin.users.empty": "Tidak ada peserta yang ditemukan.",

  "admin.match.title": "Panel Kontrol Pertandingan",
  "admin.match.finalize_confirm": "Apakah Anda yakin ingin menyelesaikan pertandingan ini? Peringkat akan dikunci.",
  "admin.match.remove_confirm": "Apakah Anda yakin ingin mengeluarkan peserta ini dari pertandingan?",
  "admin.match.not_found": "Pertandingan Tidak Ditemukan",
  "admin.match.back": "Kembali ke Kompetisi",
  "admin.match.search": "Cari peserta...",
  "admin.match.rank": "Peringkat",
  "admin.match.account": "Akun",
  "admin.match.from": "Asal",
  "admin.match.location": "Lokasi",
  "admin.match.points": "Poin",
  "admin.match.action": "Aksi",
  "admin.match.empty": "Tidak ada peserta yang ditemukan.",
  "admin.match.edit_score": "Edit",
  "admin.match.remove": "Hapus",
  "admin.match.locked": "Terkunci",
  "admin.match.add_participant": "Tambah",
  "admin.match.select_desc": "Pilih peserta untuk ditambahkan ke pertandingan ini.",
  "admin.match.select_placeholder": "-- Pilih Peserta --",
  "admin.match.cancel": "Batal",
  "admin.match.add_btn": "Tambah",
  "admin.match.edit_points": "Edit",
  "admin.match.update_score_for": "Perbarui",
  "admin.match.save": "Simpan",

  "admin.common.category": "Kategori",
  "admin.common.subject": "Mata Pelajaran",
  "admin.common.phase": "Fase",
  "admin.common.search_matches": "Cari pertandingan...",
  "admin.common.search_finalist": "Cari finalis...",
  "admin.common.email_placeholder": "kontak@contoh.com",
  "admin.common.phone_placeholder": "+62xxx",
  "admin.common.school_placeholder": "Nama Sekolah / Institusi",
  "admin.common.city_placeholder": "Cth. Surabaya",

  "admin.common.status": "Status",
  "admin.common.type": "Tipe",
  "admin.common.select_category": "Pilih Kategori",
  "admin.common.select_subject": "Pilih Mata Pelajaran",
  "admin.common.select_phase": "Pilih Fase",
  "admin.common.all_categories": "Semua Kategori",
  "admin.common.all_phases": "Semua Fase",
  "admin.common.select_bracket_type": "Pilih Tipe Braket",
  "admin.common.title_placeholder": "Cth. Cerdas Cermat Online",
  "admin.common.desc_placeholder": "Tuliskan detail kompetisi, hadiah...",
  "admin.common.fee_placeholder": "Rp 0 (Gratis)",
  "admin.common.total_prize_placeholder": "Total Keseluruhan",
  "admin.common.reward_placeholder": "Rp / Hadiah",

  "admin.common.label_title": "Judul",
  "admin.common.label_desc": "Deskripsi",
  "admin.common.label_rules": "Aturan",
  "admin.common.label_poster": "Poster",
  "admin.common.label_schedule": "Jadwal",
  "admin.common.label_registration_link": "Tautan Pendaftaran",
  "admin.common.label_registration_fee": "Biaya Pendaftaran",
  "admin.common.label_separate_subject": "Pisahkan berdasarkan Bidang",
  "admin.common.label_bracket_config": "Konfigurasi Braket",
  "admin.common.label_limit_participants": "Tetapkan Batas Peserta",
  "admin.common.label_progression": "Detail Progresi",
  "admin.common.label_match_time": "Waktu Pertandingan",
  "admin.common.label_specific_subject": "Bidang Tertentu",
  "admin.common.label_group": "Grup",
  "admin.common.label_participant_type": "Tipe Peserta",
  "admin.common.label_name": "Nama",
  "admin.common.label_email": "Email",
  "admin.common.label_phone": "Telepon",
  "admin.common.label_school": "Sekolah",
  "admin.common.label_city": "Kota",
  "admin.common.label_payment": "Pembayaran",
  "admin.common.optional": "(opsional)",

  "admin.common.add_participant": "Tambah",
  "admin.common.registration_full": "Pendaftaran penuh",
  "admin.common.add_new_participant": "Tambah",
  "admin.common.account": "Akun",
  "admin.common.from": "Asal",
  "admin.common.location": "Lokasi",
  "admin.common.registered": "Terdaftar",
  "admin.common.saving": "Menyimpan...",
  "admin.common.no_matches_found": "Tidak ada pertandingan yang cocok.",
  "admin.common.generate_matches_first": "Buat pertandingan terlebih dahulu untuk melihat braket.",
  "admin.common.action": "Aksi",
  "admin.common.avg_score": "Rata-rata Skor",
  "admin.common.no_matching_finalists": "Tidak ada finalis yang cocok atau semua sudah masuk ke braket pada fase ini.",
  "admin.common.no_bracket_data": "Belum ada data braket.",

  // Admin Receptionist & Attendance
  "admin.attendance_logs.title": "Audit Jejak Kehadiran",
  "admin.attendance_logs.heading": "Log Cek-in",
  "admin.attendance_logs.description": "Jejak audit keamanan dari semua verifikasi resepsionis.",
  "admin.attendance_logs.time": "Waktu",
  "admin.attendance_logs.participant": "Peserta",
  "admin.attendance_logs.competition": "Kompetisi",
  "admin.attendance_logs.status": "Status",
  "admin.attendance_logs.verified_by": "Diverifikasis",
  "admin.attendance_logs.notes": "Catatan",
  "admin.attendance_logs.security": "Keamanan",
  "admin.attendance_logs.loading": "Memuat jejak audit...",
  "admin.attendance_logs.empty": "Tidak ada catatan verifikasi ditemukan.",
  "admin.attendance_logs.snapshot": "Cuplikan",
  "admin.attendance_logs.no_snapshot": "Tidak Ada Cuplikan",
  "admin.attendance_logs.unknown": "Tidak Diketahui",

  "admin.receptionist.title": "Manajemen Resepsionis",
  "admin.receptionist.back": "Kembali ke Kompetisi",
  "admin.receptionist.loading": "Memuat data resepsionis...",
  "admin.receptionist.invite": "Undang",
  "admin.receptionist.invite_desc": "Bagikan kode undangan ini atau kode QR dengan resepsionis Anda agar mereka dapat bergabung secara instan.",
  "admin.receptionist.invite_code": "Kode Undangan",
  "admin.receptionist.copied": "Disalin ke papan klip!",
  "admin.receptionist.scan_desc": "Pindai kode ini menggunakan Aplikasi Resepsionis.",
  "admin.receptionist.requests": "Permintaan",
  "admin.receptionist.requests_desc": "Kelola siapa yang memiliki akses untuk memindai tiket.",
  "admin.receptionist.total": "Total",
  "admin.receptionist.name": "Nama",
  "admin.receptionist.email": "Email",
  "admin.receptionist.status": "Status",
  "admin.receptionist.actions": "Aksi",
  "admin.receptionist.empty": "Belum ada resepsionis yang meminta akses.",
  "admin.receptionist.remove_confirm": "Apakah Anda yakin ingin menghapus resepsionis ini?",

  // Profil
  "profile.title": "Profil",
  "profile.desc": "Kelola informasi pribadi dan detail kontak Anda.",
  "profile.basic_info": "Informasi Dasar",
  "profile.username": "@Username",
  "profile.username_placeholder": "Pilih username",
  "profile.fullname": "Nama Lengkap",
  "profile.fullname_placeholder": "Nama lengkap",
  "profile.email": "Email",
  "profile.phone": "Nomor Telepon",
  "profile.phone_placeholder": "+62...",
  "profile.identity": "Identitas & Institusi",
  "profile.doc_type": "Tipe Dokumen",
  "profile.doc_type_ktp": "KTP",
  "profile.doc_type_student": "Kartu Pelajar",
  "profile.doc_type_other": "Lainnya",
  "profile.doc_number": "Nomor Dokumen",
  "profile.doc_number_placeholder": "NIK atau NISN",
  "profile.institution": "Nama Institusi / Sekolah",
  "profile.institution_placeholder": "Cth: SMA Negeri 1",
  "profile.additional_info": "Informasi Tambahan",
  "profile.birth_date": "Tanggal Lahir",
  "profile.address": "Alamat Lengkap",
  "profile.address_placeholder": "Alamat tempat tinggal lengkap",
  "profile.save": "Simpan",

  // Verifikasi
  "verify.step1_title": "Unggah Kartu Identitas",
  "verify.step2_title": "Deteksi Wajah",
  "verify.step3_title": "Konfirmasi Data",
  "verify.step1_desc": "Harap berikan foto KTP atau Kartu Pelajar yang jelas.",
  "verify.step2_desc": "Posisikan wajah di dalam bingkai dan ikuti instruksi.",
  "verify.step3_desc": "Harap periksa data yang diekstraksi dari kartu identitas Anda.",
  "verify.doc_title": "Kartu Identitas",
  "verify.uploaded": "Diunggah",
  "verify.select_image": "Pilih Gambar",
  "verify.select_image_desc": "Pastikan teks dan foto di kartu terlihat jelas",
  "verify.next": "Selanjutnya",
  "verify.cancel": "Batal",
  "verify.liveness_title": "Deteksi Wajah",
  "verify.verified": "Terverifikasi",
  "verify.position_face": "Posisikan wajah Anda di dalam bingkai dan ikuti instruksi.",
  "verify.open_camera": "Buka Kamera",
  "verify.start": "Mulai",
  "verify.identity_matched": "Identitas Cocok",
  "verify.back": "Kembali",
  "verify.process_doc": "Proses",
  "verify.confirm_desc": "Harap konfirmasi data yang diekstrak.",
  "verify.id_number": "Nomor Identitas",
  "verify.fullname": "Nama Lengkap",
  "verify.birth_date": "Tanggal Lahir",
  "verify.full_address": "Alamat Lengkap",
  "verify.province": "Provinsi",
  "verify.select_province": "Pilih Provinsi",
  "verify.regency": "Kabupaten / Kota",
  "verify.select_regency": "Pilih Kab/Kota",
  "verify.district": "Kecamatan",
  "verify.select_district": "Pilih Kecamatan",
  "verify.village": "Desa / Kelurahan",
  "verify.select_village": "Pilih Desa/Kelurahan",
  "verify.street_details": "Detail Jalan",
  "verify.street_placeholder": "Detail Jalan, RT/RW, Perumahan, dsb.",
  "verify.document": "Dokumen",
  "verify.institution": "Institusi",
  "verify.confirm": "Konfirmasi",

  // Registration
  "register.verified_identity": "Terverifikasi",
  "register.registration_details": "Detail Pendaftaran",
  "register.options_desc": "Pilih opsi kompetisi berdasarkan dokumen terverifikasi Anda.",
  "register.category": "Kategori",
  "register.subject": "Subjek",
  "register.select_category": "Pilih Kategori",
  "register.select_subject": "Pilih Subjek",
  "register.full": "Penuh",
  "register.already_registered": "Terdaftar",
  "register.locked": "Terkunci",
  "register.submit": "Daftar",

  // Receptionist Scanner
  "receptionist.ticket.scanner_title": "Pemindai",
  "receptionist.ticket.open_scanner": "Buka Pemindai",
  "receptionist.ticket.scan_instructions": "Posisikan kode QR di tengah bingkai untuk memindai.",
  "receptionist.ticket.switch_camera": "Ganti Kamera",
  "receptionist.ticket.stop_scanner": "Tutup Pemindai",

  "receptionist.ticket.detail_title": "Verifikasi Tiket",
  "receptionist.ticket.participant_info": "Informasi Peserta",
  "receptionist.ticket.status": "Status",
  "receptionist.ticket.security_check": "Pemeriksaan Keamanan",
  "receptionist.ticket.security_check_1": "Selalu bandingkan",
  "receptionist.ticket.security_check_live": "Foto Langsung",
  "receptionist.ticket.security_check_2": "dengan orang yang ada di depan Anda.",
  "receptionist.ticket.security_check_3": "Jika wajah tidak cocok, klik",
  "receptionist.ticket.security_check_reject": "Tolak",
  "receptionist.ticket.security_check_4": "dan informasikan keamanan.",

  "receptionist.ticket.competition_details": "Detail Kompetisi",
  "receptionist.ticket.from": "Dari",
  "receptionist.ticket.category": "Kategori",
  "receptionist.ticket.subject": "Subjek",
  "receptionist.ticket.registered_at": "Mendaftar Pada",

  "receptionist.ticket.approve": "Check-in",
  "receptionist.ticket.flag": "Tandai",
  "receptionist.ticket.reject": "Tolak",

  "receptionist.ticket.notes_title": "Catatan",
  "receptionist.ticket.reason_notes": "Alasan",
  "receptionist.ticket.reason_placeholder": "Cth: Wajah tidak cocok, dokumen tidak valid...",
  "receptionist.ticket.cancel": "Batal",
  "receptionist.ticket.submit": "Kirim",

  // Dynamic Options
  "options.category.pra_sekolah": "TK",
  "options.category.sd": "SD",
  "options.category.smp": "SMP",
  "options.category.sma": "SMA",
  "options.category.mahasiswa": "Mahasiswa",
  "options.category.umum": "Umum",
  "options.category.profesional": "Profesional",

  "options.subject.matematika": "Matematika",
  "options.subject.sains": "Sains",
  "options.subject.bahasa_inggris": "Bahasa Inggris",
  "options.subject.fisika": "Fisika",
  "options.subject.kimia": "Kimia",
  "options.subject.biologi": "Biologi",
  "options.subject.it": "IT & Pemrograman",

  "options.subject.sejarah": "Sejarah",
  "options.subject.geografi": "Geografi",
  "options.subject.ekonomi": "Ekonomi",
  "options.subject.sosiologi": "Sosiologi",
  "options.subject.akuntansi": "Akuntansi",
  "options.subject.seni_rupa": "Seni Rupa",
  "options.subject.musik": "Musik",
  "options.subject.sastra": "Sastra",
  "options.subject.bahasa_indonesia": "Bahasa Indonesia",
  "options.subject.bahasa_mandarin": "Bahasa Mandarin",
  "options.subject.bahasa_arab": "Bahasa Arab",
  "options.subject.robotika": "Robotika",
  "options.subject.pendidikan_jasmani": "Pendidikan Jasmani",
  "options.subject.agama": "Pendidikan Agama",
  "options.subject.pkn": "PKn",
  "options.subject.informatika": "Informatika",
  "options.subject.tik": "TIK",
  "options.subject.elektronika": "Elektronika",
  "options.subject.mesin": "Mesin",
  "options.subject.kewirausahaan": "Kewirausahaan",

  "options.doc_type.ktp": "KTP",
  "options.doc_type.kartu_pelajar": "Kartu Pelajar",
  "options.doc_type.sim": "SIM",
  "options.doc_type.paspor": "Paspor",
  "options.doc_type.lainnya": "Lainnya",

  "edit.schedule.auto_schedule": "Isi Otomatis",
  "edit.schedule.match_time": "Waktu Pertandingan",
  "add.title": "Judul",
  "add.title_placeholder": "Cth: Cerdas Cermat Online - Sains",
  "add.description": "Deskripsi",
  "add.description_placeholder": "Tulis detail kompetisi, hadiah, dll.",
  "add.rules": "Aturan",
  "add.poster": "Poster",
  "add.type": "Tipe",
  "add.type_placeholder": "Pilih Tipe Kompetisi",
  "add.individual": "Individu",
  "add.team": "Tim",
  "add.general": "Umum",
  "add.private": "Privat",
  "add.prize_pool": "Total Hadiah",
  "add.registration": "Registrasi",
  "add.registration_fee": "Biaya Registrasi",
  "add.qualification": "Kualifikasi",
  "add.grand_final": "Grand Final",
  "add.category": "Kategori",
  "add.subject": "Bidang Lomba",
  "add.schedule": "Jadwal",
  "add.done": "Selesai",
  "add.draft": "Draf",
  "add.publish": "Terbitkan",
  "add.status": "Status",
  "add.registration_link": "Link Registrasi",
  "add.split_by_subject": "Pisahkan per Bidang",
  "add.use_dynamic_registration": "Gunakan Biaya Registrasi Dinamis",
  "add.standard_registration_fee": "Biaya Registrasi Standar",
  "add.tournament_configuration": "Konfigurasi Turnamen",
  "add.bracket_configuration": "Konfigurasi Braket",
  "add.select_bracket_type": "Pilih Tipe Braket",
  "add.single_elimination": "Sistem Gugur Tunggal",
  "add.double_elimination": "Sistem Gugur Ganda",
  "add.round_robin": "Sistem Kompetisi Penuh",
  "add.swiss_system": "Sistem Swiss",
  "add.set_participants_limit": "Atur Batas Peserta",
  "add.unlimited_participants": "Peserta Tidak Terbatas",
  "add.progression_details": "Detail Progresi",
  "add.semifinal_groups": "Grup Semifinal",
  "add.to_semifinal": "Menuju Semifinal",
  "add.to_final": "Menuju Final",
  "add.to_grandfinal": "Menuju Grandfinal",
  "add.to_qualification": "Menuju Kualifikasi",
  "add.to_upper_bracket": "Menuju Upper Bracket",
  "add.to_lower_bracket": "Menuju Lower Bracket",
  "add.to_group_stage": "Menuju Fase Grup",
  "add.to_knockout_stage": "Menuju Fase Knockout",
  "add.total_rounds": "Total Ronde",
  "add.to_playoffs": "Menuju Playoff",
  "add.bracket": "Braket",
  "add.bracket_preview": "Tampilan braket berdasarkan jadwal.",
  "add.please_add_matches": "Silakan tambah atau jadwalkan otomatis pertandingan",
  "add.bracket_generated_based_on_schedule": "Braket akan dibuat berdasarkan jadwal.",
  "add.detailed_schedule": "Jadwal Rinci",
  "add.manage_individual_matches": "Kelola setiap pertandingan",
  "add.all_categories": "Semua Kategori",
  "add.all_phases": "Semua Fase",
  "add.general_no_category": "Umum",
  "add.no_subject_available": "Tidak ada subjek tersedia",
  "add.err_category_phase_round": "Kategori, Fase, dan Ronde harus diisi!",
  "add.err_select_subject": "Silakan pilih subjek!",
  "add.err_schedule_exists": "Jadwal ini sudah ada!",
  "add.save_match": "Simpan",
  "add.time": "Waktu",
  "add.no_matches_found": "Tidak ada pertandingan yang cocok",
  "add.unscheduled": "Belum Dijadwalkan",
  "add.fixed_price_desc": "Tetapkan satu harga tetap",
  "add.dynamic_price_desc": "Konfigurasi tingkatan harga berbeda",
  "add.edit_match": "Edit",
  "phase.qualification": "Kualifikasi",
  "phase.elimination": "Eliminasi",
  "phase.quarterfinal": "Perempat Final",
  "phase.semifinal": "Semifinal",
  "phase.final": "Final",
  "phase.grandfinal": "Grandfinal",
  "phase.upper_bracket": "Upper Bracket",
  "phase.lower_bracket": "Lower Bracket",
  "phase.group_stage": "Fase Grup",
  "phase.knockout_stage": "Fase Knockout",
  "phase.round_1": "Ronde 1",
  "phase.round_2": "Ronde 2",
  "phase.round_3": "Ronde 3",
  "phase.round_4": "Ronde 4",
  "add.1st_place": "Juara 1",
  "add.2nd_place": "Juara 2",
  "add.3rd_place": "Juara 3",
  "add.participant_type": "Tipe Peserta",
  "admin.common.participant": "Peserta"
}